# NumPyの利用
* NumPyは，Pythonで数学的な計算を高速に行うための外部ライブラリ
* Google Colab にはインストール済み
* 配列型（ndarray型）と呼ばれるデータ型のデータを主に扱う
* 配列型はリスト（list）とよく似たデータ型だが，数値だけを扱うように制限を設けている
* 配列型は演算機能を強化しているため，大量データに対してより高速な処理が可能


## NumPyのインポート
* NumPyはライブラリなので，利用する場合はインポートする必要がある
> **書式**: `import numpy as np`
* 慣例として，NumPyは「np」という名前（略名）でインポートする ⇒ 「`np.機能名`」で利用できる

## 配列操作

### 配列とは
* NumPyで扱う配列型のデータを**配列**と呼ぶ（正確には ndarrayクラスのオブジェクト）
* 配列は，`np.array`関数を使ってリストから作成できる

> **書式**： `np.array(リスト)`

In [ ]:
import numpy as np
arr = np.array([1,2,3,4]) #配列の定義
print(arr) #配列の表示

### 配列の次元
* 配列の次元とは，データを並べるために必要な方向（軸）の数のこと
* 上のコードで作成したのは 1次元配列

**1次元配列**：1方向に並ぶ 1本の列

```
[1 2 3 4]
```

**2次元配列**：2方向に並ぶ表（行 × 列）

```
[[1 2 3]
 [4 5 6]]
```

**3次元配列**：3方向に並ぶ表の集まり（奥行 x 行 × 列）

```
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
```

In [ ]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
print(a1, '\n')
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2, '\n')
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

### 配列の構造の確認
* `ndim`属性： 配列の次元
* `size`属性： 配列の要素数
* `shape`属性： 配列の形状（次元ごとの要素数）

In [ ]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
print('1次元配列：', a1.ndim, a1.size, a1.shape)
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print('2次元配列：', a2.ndim, a2.size, a2.shape)
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('3次元配列：', a3.ndim, a3.size, a3.shape)

### 配列のインデックス指定／スライス指定
* 文字列（str型）やリスト（list）などと同様に，配列に対してもインデックス指定とスライス指定ができる

In [ ]:
# 1次元配列の例
import numpy as np
a = np.array([10, 20, 30, 40, 50])
print('配列:', a)
# インデックスを指定して要素にアクセス
print('a[0]:', a[0])
print('a[2]:', a[2])
print('a[-1]:', a[-1])
# スライスを使って部分的にアクセス
print('a[1:4]:', a[1:4])
print('a[:3]:', a[:3])
print('a[2:]:', a[2:])
print('a[::2]:', a[::2]) # 2つおき

In [ ]:
# 2次元配列の例
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('配列:')
print(b)
print('形状:', b.shape)
# インデックスを指定して要素にアクセス
print('b[0, 0]:', b[0, 0])
print('b[1, 2]:', b[1, 2])
print('b[2, -1]:', b[2, -1])
# スライスを使って部分的にアクセス
print('b[0:2, 1:3]:\n', b[0:2, 1:3])    # [[2 3] [5 6]]（1-2行目、2-3列目）
print('b[:, 0]:', b[:, 0])   # [1 4 7]（全行の最初の列）
print('b[1, :]:', b[1, :])   # [4 5 6]（2行目の全列）
print('b[::2, ::2]:\n', b[::2, ::2])  # [[1 3] [7 9]]（2行おき、2列おき）

In [ ]:
# 3次元配列の例
import numpy as np
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('配列:')
print(a3)
print('形状:', a3.shape)
# インデックスを指定して要素にアクセス
print('a3[0, 0, 0]:', a3[0, 0, 0])  # 1（1-1行目、1-1列目、1-1層目）
print('a3[1, 1, 2]:', a3[1, 1, 2])  # 12（2-2行目、2-2列目、2-1層目）
print('a3[0, 1, -1]:', a3[0, 1, -1])  # 6（1-2行目、1-2列目、最後の層）
# スライスを使って部分的にアクセス
print('a3[0, :, :]:\n', a3[0, :, :])  # [[1 2 3] [4 5 6]]（1-1行目の全列、全層）
print('a3[:, 1, :]:\n', a3[:, 1, :])  # [[4 5 6] [10 11 12]]（全行の2列目、全層）
print('a3[:, :, 0]:\n', a3[:, :, 0])  # [[1 4] [7 10]]（全行の全列の1-1層目）
print('a3[::2, ::2, ::2]:\n', a3    [::2, ::2, ::2])  # [[[1] [6]] [[7] [12]]]（2行おき、2列おき、2層おき）

## 配列の基本的な演算

### 配列とスカラーの計算
* 全要素に同じ計算が一括で適用される

In [ ]:
# 1次元配列の例
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print('a + 10:', a + 10)
print('a - 1:', a - 1)
print('a * 2:', a * 2)
print('a / 2:', a / 2)
print('a ** 2:', a ** 2)

In [ ]:
# 2次元配列の例
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('b + 10:\n', b + 10)
print('b - 1:\n', b - 1)
print('b * 2:\n', b * 2)
print('b / 2:\n', b / 2)
print('b ** 2:\n', b ** 2)

### 配列同士の計算
* 同じ位置の要素同士で計算される

In [ ]:
# 1次元配列の例
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('a + b:', a + b)
print('a - b:', a - b)
print('a * b:', a * b)
print('a / b:', a / b)

In [ ]:
# 2次元配列の例
import numpy as np
b1 = np.array([[1, 2], [3, 4]])
b2 = np.array([[10, 20], [30, 40]])
print('b1 + b2:\n', b1 + b2)
print('b1 - b2:\n', b1 - b2)
print('b1 * b2:\n', b1 * b2)
print('b1 / b2:\n', b1 / b2)

### ベクトルの内積
* 1次元配列をベクトルとして考える
* 2つのベクトルの内積を計算するには，`np.dot`関数を用いる
* **参考（ベクトルの内積の定義）**：2つのベクトル $\mathbf{a} = (a_1, a_2, \dots)$, $\mathbf{b} = (b_1, b_2, \dots)$ の内積は
$\mathbf{a} \cdot \mathbf{b} = a_1 b_1 + a_2 b_2 + \cdots$

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)
print(dot)

* 演算子`@`を使っても内積を計算できる

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = a @ b
print(dot)

### 行列の積
* 2次元配列を行列として考える
* 2つの行列の積を計算するには，`np.matmul`関数を用いる
* 演算子`@`を使っても行列の積を計算できる

In [ ]:
import numpy as np
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = np.array([
    [7, 8, 9],
    [5, 6, 7]
])

C = np.matmul(A, B)
print(C)

* ベクトルと行列の積も計算できる

In [ ]:
import numpy as np
v = np.array([1, 2, 3])

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

M = np.matmul(v, A)
print(M)

### 要素の比較
* 比較演算子や論理演算子を用いて，配列の要素ごと比較することができる
* 配列に対する論理演算子は，`and`, `or`, `not`ではなく，`&`, `|`, `~`を使う

|論理演算子|意味|
|:-:|:--|
| `&` | 両者を満たす（両者ともTrueの）ときTrue |
| `\|` | どちらか片方を満たす（少なくともどちらか一方がTrueの）ときTrue |
| `~` | 満たさない（Falseの）ときTrue |

In [ ]:
# 1次元配列の例
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a > 3)
print(a == 3)
print((a > 1) & (a < 5))

In [ ]:
# 2次元配列の例
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6], [3, 2, 1]])
print(b > 2)
print(b == 2)
print((b > 1) & (b < 5))

### 条件演算（フィルタ処理）
* `配列[条件式]`で，配列からある条件を満たす要素を取り出すことができる
* 条件式の代わりに，bool型の値を要素とする同じサイズの配列を指定することもできる
* その場合は，`True`の位置に対応する要素が取り出される

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [3, 2, 1]])
print(a)
print(a[a > 2])

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [3, 2, 1]])
b = a > 2
print(a)
print(b)
print(a[b])

## 基本的な集計関数
* NumPyには，合計や平均などを計算する様々な集計用の関数が用意されている

| 関数                 | 説明         |
| ------------------ | ---------- |
| `np.sum`           | 要素の合計      |
| `np.mean`          | 要素の平均      |
| `np.max`           | 最大値        |
| `np.min`           | 最小値        |
| `np.argmax`        | 最大値のインデックス |
| `np.argmin`        | 最小値のインデックス |
| `np.var`           | 分散         |
| `np.std`           | 標準偏差       |
| `np.median`        | 中央値        |


In [ ]:
# 1次元配列の例
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
print(a1.sum())     # 全要素の合計
print(a1.mean())    # 全要素の平均
print(a1.max())     # 最大値
print(a1.min())     # 最小値

In [ ]:
# 2次元配列の例
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.sum())     # 全要素の合計
print(a.mean())    # 全要素の平均
print(a.max())     # 最大値
print(a.min())     # 最小値

* 2次元配列に対しては，軸（方向）を指定して集計することもできる
* 軸を指定する場合は，キーワード引数`axis`を設定する
>* 列ごとの集計： `axis=0`
>* 行ごとの集計： `axis=1`



In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.sum(axis=0))   # 列ごとの合計
print(a.sum(axis=1))   # 行ごとの合計

## `np.clip`関数
* `np.clip`は，配列の値を指定した範囲内に収めるための関数
* 小さすぎる値は下限に，大きすぎる値は上限に切り詰めるために用いられる

> **書式**： `np.clip(a, min_value, max_value)`
>* `a`：配列
>* `min_value`：下限
>* `max_value`：上限

In [ ]:
import numpy as np
a = np.array([-10, 50, 120, 300])
b = np.clip(a, 0, 255)
print(b)

In [ ]:
import numpy as np
a = np.array([-10, 50, 120, 300])
b = np.clip(a + 150, 0, 255)
print(b)

# 実習
* 配列`a = np.array([30, 60, 90, 10, 50, 80, 20, 70, 40, 100])`について，以下の処理を行うコードを作成・実行せよ．
>* 値が 50 以上の要素だけを取り出す
>* 取り出した要素を表示する
>* 取り出した要素の平均値を計算する
>* 計算した平均値を表示する
>* 取り出した各要素からその平均値を引いた値を計算する
>* 計算した値を表示する
* ただし，コードは以下の要件を満たすように作成すること．

**＜要件＞**
*  すでに入力されているコードは削除・変更しない
*  「`# ここにコードを記述`」のある行にだけコードを追加で記述する
*  コメントはすべて削除する
*  以下と同じ実行結果となる

**実行結果：**

```
取り出した要素: [ 60  90  50  80  70 100]
取り出した要素の平均値: 75.0
取り出した要素から平均値を引いた結果: [-15.  15. -25.   5.  -5.  25.]
```

In [ ]:
import numpy as np
a = np.array([30, 60, 90, 10, 50, 80, 20, 70, 40, 100])
values = # ここにコードを記述
print('取り出した要素:', values)
mean_value = # ここにコードを記述
print('取り出した要素の平均値:', mean_value)
result = # ここにコードを記述
print('取り出した要素から平均値を引いた結果:', result)

# PyMuPDFの利用

## PyMuPDFとは
* PyMuPDFは，PDFファイルを操作するための外部ライブラリ
* PDFファイルに対して，テキスト抽出，画像抽出，ページ画像化，検索などの機能を備えている
* PyMuPDFの詳細については，公式の「[PyMuPDF ドキュメント（日本語版）](https://pymupdf.readthedocs.io/ja/latest/)」などを参照する（今回は基本的な機能のみを扱う）

## PyMuPDFのインストール
* PyMuPDFは外部ライブラリなので，利用する場合は，事前にインストールする必要がある
* 以下のコマンドを実行するとインストールが始まる
* 実行後，一番下に「Successfully installed PyMuPDF-X.XX.X」と表示されていれば，インストール成功（「X.XX.X」はバージョンを表す数値）

In [ ]:
%pip install PyMuPDF

## PDFファイルのダウンロード
* 今回は日本大学商学部の「商学部要覧2025」を用いる（出典: 日本大学商学部サイト内「[情報公開](https://www.bus.nihon-u.ac.jp/education-information/#gsc.tab=0)」）
* 前回と同様にして，以下のコマンドを実行し，PDFファイルをダウンロードする
* ダウンロードしたファイルは，「yoran2025.pdf」という名前でノートブック上に保存される
* ファイルは画面左側のサイドバーから確認できる
* ノートブックをしばらく操作しないと，接続切れとなりファイルは自動的に削除される

In [ ]:
!curl -L -o yoran2025.pdf https://raw.githubusercontent.com/yoshida-nu/lecture_public/main/programming/resources/yoran2025.pdf

## PyMuPDFのインポート
* PyMuPDFはライブラリなので，利用する場合はインポートする必要がある
> **書式**: `import pymupdf`

## PDFファイルの読み込み
* PDFファイルの読み込みは，`pymupdf.open`関数を用いる（組み込み関数の`open`ではないことに注意する）
> **書式**: `pymupdf.open('ファイル名')`
* 組み込みの`open`関数でPDFファイルを読み込むこともできるが，生成されるオブジェクトが異なる（一般的に`open`関数でPDFファイルを読み込むことはされない）
* `pymupdf.open`の戻り値のデータ型（クラス）は，pymupdf.Documentクラス
* 以降，この戻り値のことを「**ドキュメントオブジェクト**」と呼ぶ
* ドキュメントオブジェクトには，読み込んだ PDFファイルに関する様々な情報が含まれている
* ドキュメントオブジェクトは，前回扱ったファイルオブジェクトと同様の役割を持つと解釈してよい
* したがって，ファイルオブジェクト同様`pymupdf.open`関数でPDFファイルを読み込んだら，最後に`close`メソッドで閉じる（理由もファイルオブジェクトと同様）

In [ ]:
import pymupdf
doc = pymupdf.open('yoran2025.pdf')
print(type(doc))
doc.close()

## `with`文
* ファイルオブジェクトと同様に，ドキュメントオブジェクトに対しても `with`文を使うことで `close`メソッドの記述が省略できる

**`with`文の書式**:
```python
with ドキュメントオブジェクト as 変数:
    ドキュメントオブジェクトを操作する処理
```

*  ドキュメントオブジェクトは変数に代入される
*  ドキュメントオブジェクト（PDFファイル）を操作する処理は`with`ブロックとして記述する（ブロックの範囲をインデントで設定する）
*  `with`ブロックが終了すると，自動的に閉じる処理（`close`メソッド）が行われる
*  次のコードは，上のコードと同様の処理を行っている

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    print(type(doc))

## ドキュメントオブジェクトのインデックス指定
* ドキュメントオブジェクトは，文字列（str型のオブジェクト）やリスト（list型のオブジェクト）と同様に，インデックス指定ができる
* インデックスはページに対応し，1ページ目がインデックス 0 となる（ページ番号は 0 から始まる）
> **書式**: `doc[i]`
* インデックス指定`doc[i]`は，後述する`load_page`メソッドと同じ働きをする
* `doc[i]`や`load_page(i)`で取り出されるオブジェクトを「**ページオブジェクト**」と呼ぶ
* PDFのテキスト抽出は，ページオブジェクトのメソッドで行う（詳細は後述）


In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    page = doc[0]
    print(type(page))

## ドキュメントオブジェクトの基本的なメソッド・属性
* ドキュメントオブジェクトの基本的なメソッドと属性を下表に示す
* 具体的な利用例は後述

| 名前                  | 形式     | 説明                          |
| ---------------------------------------- | ------ | ----------------------------------------- |
| `page_count`        | 属性     | ページ数（int型）を返す                 |
| `metadata`          | 属性     | 文書のメタデータ（dict型）              |
| `close()`           | メソッド   | 文書を閉じ，内部リソースを解放する           |
| `load_page(i)`      | メソッド   | i 番目のページを取得（`doc[i]`と同じ）   |
| `search_page_for()` | メソッド   | 指定ページ内で文字列検索                |
| `new_page()`        | メソッド   | 新しいページを追加する                 |
| `delete_page(i)`    | メソッド   | i 番目のページを削除する                  |
| `save()`            | メソッド   | ドキュメントオブジェクトを PDF として保存する             |
| `insert_pdf()`      | メソッド   | 別の PDF からページをコピーして挿入  |


### `page_count`属性
* PDF文書のページ数は，`page_count`属性（int型）で確認できる

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    print(doc.page_count)

### `metadata`属性
* PDF に含まれるメタデータを辞書形式で返す
* メタデータとは「データそのものを説明するためのデータ」のことで，日本語では「付加情報」「説明情報」とも言われる
* 著者・タイトル・作成ソフトなどが含まれることがある（PDFファイルによって含まれている情報が異なる）

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    meta = doc.metadata
    print(meta)

### `load_page`メソッド
* 指定した番号のページを取得する
* `doc[i]`と同じ ⇒ ページオブジェクトが取り出せる

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    page = doc.load_page(0)
    print(type(page))

### `search_page_for`メソッド
* 指定したページ番号の中から，指定した文字列を検索
> **書式**: `search_page_for(ページ番号, '検索文字列')`
* 見つかった位置（座標領域）をリストで返す ⇒ リストの要素数が見つかった検索文字列の個数となる
* 座標 (x, y) はページの左上が原点 (0.0, 0.0) で，xは右に行くほど増加し，yは下に行くほど増加
* リストの要素である座標領域は，4つの数値 (x0, y0, x1, y1) で構成される（厳密には「Rectオブジェクト」）
* 座標領域とは矩形で描かれる領域のことで，左上の頂点に対応する座標が (x0, y0)で，右下の頂点に対応する座標が (x1, y1) となる

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    p = 1 # 検索対象ページ番号（0から始まる）
    rects = doc.search_page_for(p, '日本大学')
    print(f'検索したページ番号: {p + 1}')
    print(f'見つかった個数: {len(rects)}')
    print(f'検索文字列の位置: {rects}')

### `new_page`メソッド
* 文書の末尾に新しいページを追加する

### `delete_page`メソッド
* 引数で指定したページ（1ページのみ）を削除する
> **書式**: `delete_page(ページ番号)`  

### `delete_pages`メソッド
* 連続したページを削除する
> **書式（連続ページを削除）**: `delete_pages(開始ページ番号, 終了ページ番号)`

### `save`メソッド
* ドキュメントオブジェクトを PDF ファイルとして保存する
* ページ追加・削除などの後に使用する

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    print(f'追加前のページ数: {doc.page_count}')
    new_page = doc.new_page()
    print(f'追加後のページ数: {doc.page_count}')
    doc.delete_page(0) # 1ページ目を削除
    doc.delete_pages(2, 4)  # 3～5ページを削除
    print(f'削除後のページ数: {doc.page_count}')
    doc.save('modified.pdf') # 変更を保存

### `insert_pdf`メソッド
* 別の PDF から指定したページ範囲をコピー挿入する
* ページの結合や，特定ページだけを抜き出して新しい PDF を作成する用途で使われる
> **書式**: `target_doc.insert_pdf(src_doc, from_page=..., to_page=..., start_at=...)`
>* `target_doc`：コピー先（ターゲット）のドキュメントオブジェクト
>* `docsrc`：コピー元のドキュメントオブジェクト
>* from_page／to_page：コピーするページ範囲（インデックス指定と同じく 0 始まり）
>* `start_at`：ターゲットのどこへ挿入するか（デフォルト値は「-1」⇒末尾に追加）
* 次のコードでは，新規PDF（空のPDF）をターゲットとして，コピー挿入している ⇒ 抽出したページを新しいPDFにする
* 空のPDFに対応するドキュメントオブジェクト`out`は，`with`ブロックで `pymupdf.open()` によって生成する
* ただし，`out`については，`with`ブロックで`close`メソッドを呼び出して閉じる必要がある（`with`文が管理しているのは`doc`のみ）

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    out = pymupdf.open() # 空のPDF
    out.insert_pdf(doc, from_page=1, to_page=4) # 2-5ページをoutにコピー
    out.save('extracted_pages_2_to_5.pdf')
    out.close()

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    out = pymupdf.open() # 空のPDF
    out.insert_pdf(doc, from_page=14, to_page=16) # 15-17ページをoutにコピー
    out.save('extracted_pages_15_to_17.pdf')
    out.close()

### ファイルの結合
* `insert_pdf`メソッドで，2つのPDFファイル（`doc1`と`doc2`）を結合できる
> **書式**: `doc1.insert_pdf(doc2)`
* 次のコードでは，上のコードで作成した2つのファイル「extracted_pages_2_to_5.pdf」と「extracted_pages_15_to_17.pdf」を結合している

In [ ]:
import pymupdf
with pymupdf.open('extracted_pages_2_to_5.pdf') as doc1:
    doc2 = pymupdf.open('extracted_pages_15_to_17.pdf')
    doc1.insert_pdf(doc2)
    doc1.save('combined_pages.pdf')
    doc2.close()

## ページオブジェクトの基本的なメソッド・属性
* ページオブジェクトの基本的なメソッドと属性を下表に示す
* 具体的な利用例は後述

| 名前                   | 種別       | 説明           |
| -------------------- | -------- | ------------ |
| `number`             | 属性         | ページ番号（0 始まり） |
| `rect`               | 属性         | ページサイズ（座標）   |
| `get_text()`         | メソッド     | ページ内テキスト（プレーンテキスト）を抽出     |
| `get_pixmap()`       | メソッド     | ページを画像化      |
| `search_for()`       | メソッド     | ページ内検索       |
| `set_rotation()`       | メソッド     | ページ内検索       |


### `number`属性
* ページオブジェクトが何ページ目かを表す属性
* 0 始まり（1ページ目は 0）

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    p = 10 # ページ番号（0から始まる）
    page = doc[p]
    print(page.number)

### `rect`属性
* ページ全体の サイズと座標範囲を表す属性
* 左上座標 (0.0, 0.0)，右下座標 (width, height) の Rectオブジェクト
* 検索結果や画像切り出し（後述）の 基準座標として利用できる
* A4の場合は，おおよそ左上座標 (0.0, 0.0)，右下座標 (595.0, 842.0)

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    p = 10 # ページ番号（0から始まる）
    page = doc[p]
    print(page.rect)

### `get_text`メソッド
* ページ内の文字をプレーンテキスト（str型）として抽出

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    p = 1 # ページ番号（0から始まる）
    page = doc[p]
    text = page.get_text()
    print(text[:100]) # 最初の100文字を表示

### `get_pixmap`メソッド
* ページを画像（正確にはPixmapオブジェクト）に変換
* PDF から 画像ファイル（PNG / JPEG ファイル）へ変換するときに使用する

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    p = 0 # ページ番号（0から始まる）
    page = doc[p]
    pix = page.get_pixmap()
    pix.save('page.png')

### `search_for`メソッド
* ページ内で指定した文字列を検索
* 戻り値は`search_page_for`メソッドと同様（座標領域（Rectオブジェクト）のリスト）
> **書式**: `search_for('検索文字列')`

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    p = 1 # ページ番号（0から始まる）
    page = doc[p]
    rects = page.search_for('日本大学')
    print(f'検索したページ番号: {p + 1}')
    print(f'見つかった個数: {len(rects)}')
    print(f'検索文字列の位置: {rects}')

### `set_rotation`メソッド
* ページ全体の表示回転（向き）を設定
* 回転角度は，0 / 90 / 180 / 270 のいずれか
> **書式**: `set_rotation(回転角度)`

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    p = 0 # ページ番号（0から始まる）
    page = doc[p]
    page.set_rotation(90)
    doc.save('rotated.pdf') # 変更を保存

## ドキュメントオブジェクトはイテラブル
* ドキュメントオブジェクトはイテラブル ⇒ ページの先頭から順にページオブジェクトとして取り出すことができる
* したがって，ドキュメントオブジェクトを`for`文に利用することができる
* 次のコードでは，学部要覧内に「プログラミング」の記述があるページ番号を表示している
* `page.number` が `None` である可能性があるので，警告（赤い波線）が表示されるかもしれないが，この例では `page.number` が `None` にはなり得ないので警告は無視してよい

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    for page in doc:
        rects = page.search_for('プログラミング')
        if rects != []:
            print(f'{page.number + 1} ページに「プログラミング」が見つかりました。')

# 実習
* 学部要覧（yoran2025.pdf）内に「日本大学」が合計何個記述されているかを数え，その数を表示するコードを作成・実行せよ．
* ただし，コードは以下の要件を満たすように作成すること．

**＜要件＞**
*  すでに入力されているコードは削除・変更しない
*  「`# ここにコードを記述`」のある行にだけコードを追加で記述する
*  コメントはすべて削除する
*  以下と同じ実行結果となる

**実行結果：**

```
「日本大学」が見つかった総数: 82
```

In [ ]:
import pymupdf
with pymupdf.open('yoran2025.pdf') as doc:
    s = 0
    text = '日本大学'
    # ここにコードを記述
    # ここにコードを記述
    # ここにコードを記述
    print(f'「{text}」が見つかった総数: {s}')

# 参考資料
*  みやさかしんや, 作りたいものがない人のためのPython入門, 講談社, 2025
*  塚本邦尊, 山田典一, 大澤文孝, 東京大学のデータサイエンティスト育成講座 Pythonで手を動かして学ぶデ―タ分析, マイナビ出版, 2019
*  川島賢, 今すぐ試したい！ 機械学習・深層学習（ディープラーニング） 画像認識プログラミングレシピ, 秀和システム新社, 2019
